/**
 * content/cv.md  ->  src/data/cv.ts
 *
 * Run `npm run cv` after editing content/cv.md. This also runs automatically
 * before `npm run build`, so the site always matches the markdown.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parseCv } from "./cv-parse.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "content", "cv.md");
const OUT = join(root, "src", "data", "cv.ts");

const warnings = [];
const cv = parseCv(readFileSync(SRC, "utf8"), warnings);

// Basic sanity checks so a malformed edit fails loudly instead of silently
// shipping an empty CV.
const problems = [...warnings];
if (!cv.name) problems.push("missing name (expected a `# Name` heading)");
if (!cv.title) problems.push("missing title (expected a `Title:` line)");
if (!cv.bio.length) problems.push("no Profile paragraphs");
if (!cv.experience.length) problems.push("no Experience entries");
for (const e of cv.experience) {
  if (!e.role) problems.push(`"${e.company}" is missing a Role: line`);
  if (!e.period) problems.push(`"${e.company}" is missing a Dates: line`);
}
if (problems.length) {
  console.error("✗ content/cv.md problems:\n  - " + problems.join("\n  - "));
  process.exit(1);
}

const banner = `// AUTO-GENERATED from content/cv.md — do not edit this file directly.
// Edit content/cv.md, then run \`npm run cv\` (or just \`npm run build\`).
`;

const body = JSON.stringify(cv, null, 2);

writeFileSync(
  OUT,
  `${banner}import type { CVData } from "@/types/project";

export const cv: CVData = ${body};
`,
);

console.log(
  `✓ src/data/cv.ts — ${cv.experience.length} roles, ${cv.skills.length} skills, ${cv.awards.length} awards`,
);
