// AUTO-GENERATED from content/cv.md — do not edit this file directly.
// Edit content/cv.md, then run `npm run cv` (or just `npm run build`).
import type { CVData } from "@/types/project";

export const cv: CVData = {
  "name": "Jason Herring",
  "title": "Design Technologist / Principal — Creative Engineer",
  "bio": [
    "Principal-level design technologist who ships — I write the code and direct the creative. 20+ years at the seam of design and engineering. Currently shipping real customer impact with Foresight, Intuit’s AI innovation team — including the new Intuit Labs and Delphi.",
    "I’ve explored and prototyped AI-driven personality engines, conversational streaming, and real-time avatars, and led immersive workshops that give creatives and executives hands-on fluency with emerging tech. Whether I’m teaching designers to code or designing systems that feel human, I’m chasing the same question: what happens when intelligence itself becomes a creative medium?",
    "What I’m looking for next is a place to build the future with forward-thinking optimists — people who’d rather put working things in front of real users."
  ],
  "skills": [
    "Conversational AI / Voice / Multi-Modal",
    "Generative AI / LLMs / RAG",
    "Prompt Engineering",
    "AI Personality & Agentic Systems",
    "Real-Time Voice Pipelines (Vapi, LiveKit, Hume, HeyGen)",
    "Rapid Prototyping / High-Fidelity Provocation",
    "Multi-Modal Interfaces / Voice UI",
    "Product Design / UX / Design Systems / Figma",
    "Web Design / Art Direction / Visual Design",
    "Front-End Engineering (React / Next.js / TypeScript)",
    "Motion Design / Animation / Interaction Design",
    "Python / TypeScript / React / Next.js / Node.js",
    "API Design / Real-Time Systems",
    "Creative Direction / Brand & Campaign Vision",
    "Creative Strategy / Concept Development",
    "Innovation Strategy / Design Technology Leadership",
    "Workshop Facilitation / Executive Communication"
  ],
  "clients": [
    "Intuit",
    "Nike",
    "MoMA",
    "Adidas",
    "Stüssy",
    "UNDFTD",
    "Vans OTW",
    "Pepsi",
    "DreamWorks",
    "KQED",
    "HUF",
    "The North Face",
    "Rebel8",
    "BART",
    "Tracy Chapman / Elektra Records",
    "Aesop Rock / Def Jux",
    "Arta Tequila",
    "Exploratorium"
  ],
  "experience": [
    {
      "company": "Intuit",
      "role": "Senior Staff Design Technologist — Foresight (AI)",
      "period": "APR 2024 — PRESENT",
      "description": "Key builder on Foresight, Intuit’s 100+ person AI innovation team (reporting into the Chief AI Officer org). Promoted Staff → Senior Staff, and served as Group Manager (Feb–Jun 2026) before returning to a senior IC leadership track to keep building.",
      "bullets": [
        "Shipped Intuit Labs (labs.intuit.com/ai) — the internal and external-facing platform that turns AI innovation prototypes into shipping product. Live in public beta to 1M+ international users, with rollout to all of QuickBooks underway.",
        "Built both the site and the strategy behind Labs — defining how experiments graduate from speculative demo to guest-facing feature, and the surface that makes that pipeline visible inside and outside the company.",
        "Developed Labs' first experiment, the Delphi guest experience (delphi.intuit.com) — financial general intelligence that turns QuickBooks data into forward-looking, advisory recommendations.",
        "Launched QuickBooks Labs, an internal experimentation surface embedded directly inside QuickBooks proper, extending the Labs model to Intuit's core product.",
        "Spend most of my time in R&D — prototyping and pressure-testing emerging technologies as they land: generative AI, real-time voice systems, and AI personality and emotion detection (Hume).",
        "Designed and built a real-time AI personality engine from scratch — natural language, emotional intelligence, and embodied avatars — on ultra-low-latency voice pipelines (Vapi, Hume, LiveKit, HeyGen).",
        "Delivered flagship demos at executive forums and summits that shifted how leadership invests in AI as a product medium.",
        "Built org-wide AI-literacy workshops (Demystifying Python, Shipping Conversations, AI Avatars & Voice), seeding hands-on fluency across teams."
      ]
    },
    {
      "company": "Aleph",
      "role": "Director of Design and Technology",
      "period": "MAR 2020 — APR 2024",
      "description": "Creative and technical leadership for an enterprise development studio. Managed engineering, design, and client relationships across React, React Native, Node, WordPress, and UX engagements.",
      "bullets": [
        "Increased annual revenue by more than 85% over four years through new client acquisition and expanded scopes.",
        "Directed a mobile app for Helix clinical trials — notifications, dashboards, and protocol compliance tools that increased user acquisition success by 22%.",
        "Led a complete studio rebrand: logo, typography, color, brand guidelines, and AI-assisted creative direction using Midjourney.",
        "Built and managed a team of 8 engineers and 3 designers across multiple concurrent client engagements.",
        "Introduced AI workflows (ChatGPT, Midjourney, Stable Diffusion) into the studio’s design and development process."
      ]
    },
    {
      "company": "KQED",
      "role": "Lead UX Designer → Director of Digital Design and Development",
      "period": "JAN 2015 — MAR 2020",
      "description": "Joined as Lead UX Designer and was promoted to Director of Digital Design and Development — growing from hands-on product design into leading the design and technology that transformed KQED.org and the systems behind it. Helped move public media from a traditional broadcaster into a modern, audience-driven platform for millions of listeners and readers, focused on prototyping, modernization, and the technical foundation for new kinds of storytelling.",
      "bullets": [
        "The Listening Project: led a complete redesign of KQED Radio, News, Arts, Science, and the homepage — a persistent audio player, a flexible editorial content system, and a real-time “trending” experience.",
        "2016 Election Voter Guide: spearheaded one of the first single-page apps deployed by a public media org — a custom WordPress-to-Elasticsearch pipeline and React front end that became a model for civic engagement design across NPR member stations.",
        "Prototyped and built a real-time election dashboard that drew 1M+ views on election night 2016.",
        "Led the multi-year redesign of KQED.org, partnering with design, engineering, product, and AlephSF to build a modern, accessible platform for public media in the Bay Area.",
        "Rebuilt the CI/CD pipeline and migrated KQED’s massive WordPress CMS from AWS to Kubernetes on Google Cloud — enabling canary deployments and instant rollbacks while powering hundreds of thousands of articles and partner feeds (NPR, Apple News, Google News).",
        "Designed automated audio workflows for Alexa, Google Assistant, and NPR One — normalizing audio levels and publishing segmented clips for emerging voice platforms.",
        "Created real-time election infrastructure across every Bay Area county for 2018 — scrapers, editorial workflows, and automated publishing that made coverage fast and reliable."
      ]
    },
    {
      "company": "OrdinaryKids",
      "role": "Founder & Creative Director",
      "period": "JAN 2001 — JAN 2015",
      "description": "Formed in the midst of the dot-com fallout, OrdinaryKids grew into a cutting-edge generative art and creative-technology studio — over a decade of award-winning, thought-provoking work at the frontier of what the browser and code could do. Building mostly direct-to-client relationships, the studio treated code as a creative medium, shaping and augmenting brands across the skate, architecture, fashion, and music worlds.",
      "bullets": [
        "Pioneered generative and interactive work in ActionScript, Processing, and early creative-coding tools — building custom, code-driven visual systems, generative type and identity, and audio-reactive experiences years before \"creative technology\" was a discipline.",
        "Set the bar for interactive brand expression on the web, treating each site as a bespoke, experimental system rather than a template — motion, sound, and real-time behavior woven into the brand itself.",
        "Delivered flagship brand work for Nike (Skateboarding, Running, Sportswear), Adidas Skateboarding, and Brita, alongside cultural projects for MoMA, Stüssy, HUF, Tracy Chapman, and Aesop Rock — including the “None Shall Pass” music video.",
        "Recognized with How Magazine Best of Show, a Communication Arts Interactive Annual cover, and FWA Site of the Day honors; work later archived in the Taschen History of Web Design.",
        "Ran a small, tight studio that anchored the SF design scene and launched a generation of Bay Area design and creative-technology careers."
      ]
    },
    {
      "company": "DualForces",
      "role": "Partner & Creative Director",
      "period": "SEP 2010 — DEC 2013",
      "description": "A creative application studio working at the intersection of fashion, streetwear, and emerging culture — designing experiences that move fluidly between digital, physical, and cinematic worlds, merging art direction, technology, and cultural storytelling into one practice.",
      "bullets": [
        "Creative-directed the Nike Free visual center — the first public use of real Nike+ data in a marketing campaign — and produced a 56-page zine shot in London, NYC, and Tokyo.",
        "Ran the Nike FuelBand influencer campaign in NYC: 60+ events in 90 days with a large content team.",
        "Collaborated with Nike, Stüssy, UNDFTD, Vans OTW, Pepsi, DreamWorks, and SA Studios — work spanning digital products, retail environments, and large-scale installations.",
        "Produced a microsite and directed six short films for Nike NSW (Sportswear)."
      ]
    }
  ],
  "education": [
    {
      "institution": "University of South Florida, Tampa",
      "degree": "English Literature",
      "note": "Dropped out senior year. Fell in love with the library and discovered the internet."
    },
    {
      "institution": "Hillsborough Community College, Tampa",
      "degree": "Associate of Arts"
    }
  ],
  "awards": [
    "How Magazine — Best of Show, Interactive Annual",
    "FWA — Site of the Day (multiple)",
    "Communication Arts — Interactive Annual (cover)",
    "Print Magazine — MoMA Design Takes on Risk",
    "One Club — Judge",
    "Featured in History of Web Design (Taschen)"
  ],
  "references": [
    {
      "name": "Jodi Twilleger",
      "title": "ECD — Collins, Magic Leap, Hush",
      "email": ""
    },
    {
      "name": "Justin Marr",
      "title": "Design Director — Uber, Intuit",
      "email": ""
    },
    {
      "name": "Phouphet Sihavong",
      "title": "Director, Applied AI — Intuit",
      "email": ""
    },
    {
      "name": "Tim Olson",
      "title": "SVP Strategic Partnerships — KQED",
      "email": ""
    }
  ]
};
